# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-09 04:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='core.MyUser'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='year_released',
            field=models.DateField(auto_now=True, max_length=8),
        ),
    ]
