# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-10 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year_released',
            field=models.DateField(auto_now=True, max_length=8),
        ),
    ]
