# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-09 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.IntegerField(choices=[(0, 'P'), (1, 'A'), (2, 'NULL')], default=2)),
                ('sourceid', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play', to='songs.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play', to='core.MyUser')),
            ],
        ),
        migrations.AlterField(
            model_name='rate',
            name='score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0),
        ),
        migrations.AlterField(
            model_name='rate',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
