# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171209_1930'),
        ('songs', '0003_auto_20171209_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set([('user', 'song')]),
        ),
    ]
